import { useEffect, useState } from 'react';
import { CheckSquare, Circle, PlayCircle, CheckCircle2, Target } from 'lucide-react';
import { missionService } from '@/services/MissionService';
import type { Mission, Task } from '@/types/schema';
import { cn } from '@/lib/utils';

export const TasksView = () => {
  const [missions, setMissions] = useState<Mission[]>([]);
  const [tasks, setTasks] = useState<Task[]>([]);
  const [selectedMissionId, setSelectedMissionId] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const loadTasks = async () => {
      try {
        const [m, t] = await Promise.all([
          missionService.getMissions(),
          missionService.getTasks(),
        ]);
        setMissions(m);
        setTasks(t);
        if (m.length > 0) {
          setSelectedMissionId(m[0].id);
        }
      } catch (err) {
        console.error('[TasksView] Failed to load data from Lemma:', err);
      } finally {
        setLoading(false);
      }
    };
    loadTasks();
  }, []);

  const selectedMission = missions.find((m) => m.id === selectedMissionId);
  const filteredTasks = selectedMissionId
    ? tasks.filter((t) => t.missionId === selectedMissionId)
    : tasks;

  return (
    <div className="p-4 md:p-8 h-full flex flex-col font-body">
      <header className="mb-6 md:mb-8">
        <h1 className="text-2xl md:text-3xl font-heading font-bold text-text-primary flex items-center gap-3">
          <CheckSquare className="w-7 h-7 md:w-8 md:h-8 text-primary" />
          Execution Tasks
        </h1>
        <p className="text-text-secondary text-xs md:text-sm mt-1">Manage missions and sub-tasks generated by AI.</p>
      </header>

      {loading ? (
        <div className="flex-1 flex items-center justify-center bg-surface border border-gray-100 rounded-2xl">
          <div className="w-8 h-8 border-4 border-primary border-t-transparent rounded-full animate-spin"></div>
        </div>
      ) : (
        <div className="flex-1 bg-surface rounded-2xl border border-gray-100 shadow-sm overflow-hidden flex flex-col md:flex-row min-h-0">
          
          {/* Missions Sidebar / Horizontal Tab Bar on Mobile */}
          <div className="w-full md:w-80 border-b md:border-b-0 md:border-r border-gray-100 bg-gray-50/20 overflow-hidden flex flex-col shrink-0">
            <div className="p-3 md:p-4 border-b border-gray-100 bg-white md:bg-transparent hidden md:block">
              <h3 className="font-semibold text-text-primary uppercase text-[10px] md:text-xs tracking-wider">Active Missions</h3>
            </div>
            
            {/* Scrollable list (horizontal on mobile, vertical on desktop) */}
            <div className="flex flex-row md:flex-col overflow-x-auto md:overflow-x-hidden md:overflow-y-auto p-2 gap-1.5 md:gap-1 scrollbar-none">
              {missions.length === 0 ? (
                <div className="p-4 text-xs text-text-secondary italic text-center w-full">
                  No active missions found.
                </div>
              ) : (
                missions.map((m) => {
                  const missionTasks = tasks.filter((t) => t.missionId === m.id);
                  const completedCount = missionTasks.filter((t) => t.status === 'completed').length;
                  const pct = missionTasks.length > 0 ? Math.round((completedCount / missionTasks.length) * 100) : 0;
                  const isSelected = selectedMissionId === m.id;

                  return (
                    <button
                      key={m.id}
                      onClick={() => setSelectedMissionId(m.id)}
                      className={cn(
                        "text-left p-3 rounded-xl border transition-all duration-150 shrink-0 md:shrink-1 flex flex-col justify-between",
                        "w-56 md:w-full min-h-[70px] md:min-h-0", // fixed width on mobile
                        isSelected
                          ? 'bg-white border-primary/25 shadow-sm shadow-primary/5'
                          : 'border-transparent hover:bg-gray-100/50'
                      )}
                    >
                      <div className={cn(
                        "font-semibold text-xs md:text-sm truncate w-full",
                        isSelected ? 'text-primary' : 'text-text-primary'
                      )}>
                        {m.title}
                      </div>
                      <div className="text-[10px] text-text-secondary flex justify-between items-center mt-2 w-full">
                        <span>{m.targetDate ? `Due ${m.targetDate}` : 'No deadline'}</span>
                        <span className="bg-secondary text-primary px-1.5 py-0.5 rounded font-bold text-[9px]">{pct}%</span>
                      </div>
                    </button>
                  );
                })
              )}
            </div>
          </div>

          {/* Task List container */}
          <div className="flex-1 overflow-y-auto p-4 md:p-6 flex flex-col min-h-0">
            {selectedMission ? (
              <>
                <div className="mb-5 md:mb-6">
                  <h2 className="font-heading font-black text-lg md:text-xl text-text-primary">{selectedMission.title}</h2>
                  <p className="text-xs md:text-sm text-text-secondary mt-1">{selectedMission.description}</p>
                </div>

                {filteredTasks.length === 0 ? (
                  <div className="flex-1 flex flex-col items-center justify-center text-text-secondary italic text-sm">
                    No steps planned for this mission yet.
                  </div>
                ) : (
                  <div className="space-y-2.5 md:space-y-3">
                    {filteredTasks.map((task) => (
                      <div
                        key={task.id}
                        className={cn(
                          "flex items-start gap-3.5 p-4 rounded-xl border transition-all duration-150",
                          task.status === 'completed'
                            ? 'border-gray-100 bg-gray-50/50 opacity-60'
                            : task.status === 'in_progress'
                            ? 'border-primary/25 bg-secondary/5 relative overflow-hidden'
                            : 'border-gray-100 bg-white hover:border-gray-200'
                        )}
                      >
                        {task.status === 'in_progress' && (
                          <div className="absolute left-0 top-0 bottom-0 w-1 bg-primary"></div>
                        )}
                        <div className="mt-0.5 shrink-0">
                          {task.status === 'completed' && <CheckCircle2 className="w-4.5 h-4.5 text-primary" />}
                          {task.status === 'in_progress' && <PlayCircle className="w-4.5 h-4.5 text-primary animate-pulse" />}
                          {task.status === 'todo' && <Circle className="w-4.5 h-4.5 text-gray-300" />}
                        </div>
                        <div className="flex-1 min-w-0">
                          <h4
                            className={cn(
                              "font-semibold text-xs md:text-sm text-text-primary",
                              task.status === 'completed' && 'line-through text-text-secondary'
                            )}
                          >
                            {task.title}
                          </h4>
                          {task.description && (
                            <p className="text-[11px] md:text-xs text-text-secondary mt-1 leading-relaxed">
                              {task.description}
                            </p>
                          )}
                        </div>
                        {task.estimatedDuration && (
                          <span className="text-[9px] bg-gray-100 text-text-secondary px-1.5 py-0.5 rounded font-medium shrink-0">
                            {task.estimatedDuration}m
                          </span>
                        )}
                      </div>
                    ))}
                  </div>
                )}
              </>
            ) : (
              <div className="flex-1 flex flex-col items-center justify-center text-text-secondary text-sm py-12">
                <Target className="w-12 h-12 text-gray-300 mb-2 animate-bounce" />
                <span>Select a mission above to view the generated roadmap.</span>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
};
