import { useEffect, useState } from 'react';
import { CheckSquare, Circle, PlayCircle, CheckCircle2, Target } from 'lucide-react';
import { missionService } from '@/services/MissionService';
import type { Mission, Task } from '@/types/schema';

export const TasksView = () => {
  const [missions, setMissions] = useState<Mission[]>([]);
  const [tasks, setTasks] = useState<Task[]>([]);
  const [selectedMissionId, setSelectedMissionId] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const loadTasks = async () => {
      try {
        const [m, t] = await Promise.all([
          missionService.getMissions(),
          missionService.getTasks(),
        ]);
        setMissions(m);
        setTasks(t);
        if (m.length > 0) {
          setSelectedMissionId(m[0].id);
        }
      } catch (err) {
        console.error('[TasksView] Failed to load data from Lemma:', err);
      } finally {
        setLoading(false);
      }
    };
    loadTasks();
  }, []);

  const selectedMission = missions.find((m) => m.id === selectedMissionId);
  const filteredTasks = selectedMissionId
    ? tasks.filter((t) => t.missionId === selectedMissionId)
    : tasks;

  return (
    <div className="p-8 h-full flex flex-col font-body">
      <header className="mb-8">
        <h1 className="text-3xl font-heading font-bold text-text-primary flex items-center gap-3">
          <CheckSquare className="w-8 h-8 text-primary" />
          Execution Tasks
        </h1>
        <p className="text-text-secondary mt-1">Manage missions and sub-tasks generated by AI.</p>
      </header>

      {loading ? (
        <div className="flex-1 flex items-center justify-center bg-surface border border-gray-100 rounded-2xl">
          <div className="w-8 h-8 border-4 border-primary border-t-transparent rounded-full animate-spin"></div>
        </div>
      ) : (
        <div className="flex-1 bg-surface rounded-2xl border border-gray-100 shadow-sm overflow-hidden flex min-h-0">
          {/* Missions Sidebar */}
          <div className="w-1/3 border-r border-gray-100 bg-gray-50/30 overflow-y-auto">
            <div className="p-4 border-b border-gray-100">
              <h3 className="font-semibold text-text-primary uppercase text-xs tracking-wider">Active Missions</h3>
            </div>
            <div className="p-2 space-y-1">
              {missions.length === 0 ? (
                <div className="p-4 text-xs text-text-secondary italic text-center">
                  No active missions found.
                </div>
              ) : (
                missions.map((m) => {
                  const missionTasks = tasks.filter((t) => t.missionId === m.id);
                  const completedCount = missionTasks.filter((t) => t.status === 'completed').length;
                  const pct = missionTasks.length > 0 ? Math.round((completedCount / missionTasks.length) * 100) : 0;
                  const isSelected = selectedMissionId === m.id;

                  return (
                    <button
                      key={m.id}
                      onClick={() => setSelectedMissionId(m.id)}
                      className={`w-full text-left p-3 rounded-xl border transition-all ${
                        isSelected
                          ? 'bg-white border-primary/20 shadow-sm shadow-primary/5'
                          : 'border-transparent hover:bg-gray-100/50'
                      }`}
                    >
                      <div className={`font-semibold mb-1 ${isSelected ? 'text-primary' : 'text-text-primary'}`}>
                        {m.title}
                      </div>
                      <div className="text-xs text-text-secondary flex justify-between items-center mt-1.5">
                        <span>{m.targetDate ? `Due ${m.targetDate}` : 'No target date'}</span>
                        <span className="bg-secondary text-primary px-1.5 py-0.5 rounded font-medium">{pct}%</span>
                      </div>
                    </button>
                  );
                })
              )}
            </div>
          </div>

          {/* Task List */}
          <div className="flex-1 overflow-y-auto p-6 flex flex-col">
            {selectedMission ? (
              <>
                <div className="mb-6">
                  <h2 className="font-heading font-bold text-xl text-text-primary">{selectedMission.title} - Tasks</h2>
                  <p className="text-sm text-text-secondary mt-1">{selectedMission.description}</p>
                </div>

                {filteredTasks.length === 0 ? (
                  <div className="flex-1 flex flex-col items-center justify-center text-text-secondary italic text-sm">
                    No steps planned for this mission yet.
                  </div>
                ) : (
                  <div className="space-y-3">
                    {filteredTasks.map((task) => (
                      <div
                        key={task.id}
                        className={`flex items-start gap-4 p-4 rounded-xl border transition-all ${
                          task.status === 'completed'
                            ? 'border-gray-100 bg-gray-50/50 opacity-60'
                            : task.status === 'in_progress'
                            ? 'border-primary bg-secondary/10 relative overflow-hidden'
                            : 'border-gray-100 bg-white hover:border-gray-200'
                        }`}
                      >
                        {task.status === 'in_progress' && (
                          <div className="absolute left-0 top-0 bottom-0 w-1 bg-primary"></div>
                        )}
                        <div className="mt-0.5 shrink-0">
                          {task.status === 'completed' && <CheckCircle2 className="w-5 h-5 text-primary" />}
                          {task.status === 'in_progress' && <PlayCircle className="w-5 h-5 text-primary animate-pulse" />}
                          {task.status === 'todo' && <Circle className="w-5 h-5 text-gray-300" />}
                        </div>
                        <div className="flex-1">
                          <h4
                            className={`font-medium ${
                              task.status === 'completed' ? 'text-text-primary line-through' : 'text-text-primary'
                            }`}
                          >
                            {task.title}
                          </h4>
                          {task.description && (
                            <p className="text-sm text-text-secondary mt-1">{task.description}</p>
                          )}
                        </div>
                        {task.estimatedDuration && (
                          <span className="text-xs bg-gray-100 text-text-secondary px-2 py-0.5 rounded">
                            {task.estimatedDuration}m
                          </span>
                        )}
                      </div>
                    ))}
                  </div>
                )}
              </>
            ) : (
              <div className="flex-1 flex flex-col items-center justify-center text-text-secondary text-sm">
                <Target className="w-12 h-12 text-gray-300 mb-2" />
                Select a mission on the left to view the generated roadmap.
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
};
